// cp2_6.20_auto36/src/components/Visualizer.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { useMusicStore, getNoteColor } from '@/stores/musicStore'
import { getCurrentVolume } from '@/utils/audioEngine'

const store = useMusicStore()
const canvasRef = ref<HTMLCanvasElement | null>(null)
const containerRef = ref<HTMLDivElement | null>(null)
let ctx: CanvasRenderingContext2D | null = null
let rafId: number | null = null

interface LightPoint {
  x: number
  y: number
  baseRadius: number
  startTime: number
  duration: number
  color: string
  noteIndex: number
}
const lightPoints: LightPoint[] = []
const renderedIds = new Set<string>()

function addLightPoint(noteIndex: number, id: string, color: string, now: number) {
  if (!canvasRef.value) return
  const w = canvasRef.value.width
  const h = canvasRef.value.height
  const cx = w / 2
  const noteY = h - 30 - (noteIndex / 23) * (h - 80)
  lightPoints.push({
    x: cx + (Math.random() - 0.5) * 20,
    y: noteY,
    baseRadius: 8,
    startTime: now,
    duration: 200,
    color,
    noteIndex
  })
  renderedIds.add(id)
}

watch(
  () => store.activeNotes.map(a => a.placedNoteId),
  (ids) => {
    const now = performance.now()
    for (const active of store.activeNotes) {
      if (!renderedIds.has(active.placedNoteId)) {
        addLightPoint(active.index, active.placedNoteId, getNoteColor(active.index), now)
      }
    }
    for (const id of Array.from(renderedIds)) {
      if (!ids.includes(id)) {
        renderedIds.delete(id)
      }
    }
  },
  { deep: true }
)

function drawNoteLines(w: number, h: number) {
  if (!ctx) return
  ctx.strokeStyle = 'rgba(99, 102, 241, 0.08)'
  ctx.lineWidth = 1
  for (let i = 0; i <= 23; i++) {
    const y = h - 30 - (i / 23) * (h - 80)
    ctx.beginPath()
    ctx.moveTo(40, y)
    ctx.lineTo(w - 20, y)
    ctx.stroke()
  }
  for (let i = 0; i <= 23; i += 6) {
    const y = h - 30 - (i / 23) * (h - 80)
    ctx.fillStyle = 'rgba(148, 163, 184, 0.5)'
    ctx.font = '10px sans-serif'
    ctx.fillText(i < 12 ? `C${4 + Math.floor(i / 12)}` : `C${4 + Math.floor(i / 12)}`, 10, y + 3)
  }
}

function render() {
  if (!ctx || !canvasRef.value) return
  const w = canvasRef.value.width
  const h = canvasRef.value.height
  ctx.clearRect(0, 0, w, h)

  ctx.fillStyle = 'rgba(15, 23, 42, 0.4)'
  ctx.fillRect(0, 0, w, h)

  drawNoteLines(w, h)

  const volume = getCurrentVolume()
  const now = performance.now()

  for (let i = lightPoints.length - 1; i >= 0; i--) {
    const lp = lightPoints[i]
    const age = now - lp.startTime
    if (age >= lp.duration) {
      lightPoints.splice(i, 1)
      continue
    }
    const t = age / lp.duration
    const volumeBoost = 1 + volume * 1.2
    const radius = (8 + volume * 12) * (1 - t * 0.5)
    const alpha = 1 - t

    const grad = ctx.createRadialGradient(lp.x, lp.y, 0, lp.x, lp.y, radius * 2.5)
    grad.addColorStop(0, lp.color)
    grad.addColorStop(0.4, lp.color + 'aa')
    grad.addColorStop(1, 'transparent')

    ctx.save()
    ctx.globalAlpha = alpha
    ctx.shadowBlur = 20 + volume * 20
    ctx.shadowColor = lp.color
    ctx.fillStyle = grad
    ctx.beginPath()
    ctx.arc(lp.x, lp.y, radius * 2.5, 0, Math.PI * 2)
    ctx.fill()

    ctx.shadowBlur = 0
    ctx.fillStyle = '#fff'
    ctx.beginPath()
    ctx.arc(lp.x, lp.y, radius * 0.4, 0, Math.PI * 2)
    ctx.fill()
    ctx.restore()
    void volumeBoost
    void lp.baseRadius
  }

  rafId = requestAnimationFrame(render)
}

function resize() {
  if (!canvasRef.value || !containerRef.value) return
  const dpr = window.devicePixelRatio || 1
  const rect = containerRef.value.getBoundingClientRect()
  canvasRef.value.width = rect.width * dpr
  canvasRef.value.height = rect.height * dpr
  canvasRef.value.style.width = rect.width + 'px'
  canvasRef.value.style.height = rect.height + 'px'
  if (ctx) ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
  if (ctx) (ctx as any)._width = rect.width, (ctx as any)._height = rect.height
}

onMounted(() => {
  if (canvasRef.value) {
    ctx = canvasRef.value.getContext('2d')
    resize()
    window.addEventListener('resize', resize)
    render()
  }
})

onUnmounted(() => {
  window.removeEventListener('resize', resize)
  if (rafId) cancelAnimationFrame(rafId)
})
</script>

<template>
  <div ref="containerRef" class="visualizer">
    <div class="viz-header">
      <h3 class="viz-title">实时可视化</h3>
      <div class="viz-legend">
        <span class="legend-dot low"></span>
        <span class="legend-text">低音</span>
        <span class="legend-dot high"></span>
        <span class="legend-text">高音</span>
      </div>
    </div>
    <div class="viz-canvas-wrap">
      <canvas ref="canvasRef" class="viz-canvas"></canvas>
      <div v-if="store.activeNotes.length === 0" class="viz-empty">
        <div class="empty-hint">播放以查看光点动画</div>
      </div>
    </div>
    <div class="active-notes">
      <div class="active-label">激活音符:</div>
      <div class="active-list">
        <span
          v-for="a in store.activeNotes"
          :key="a.placedNoteId"
          class="active-badge"
          :style="{ background: getNoteColor(a.index) }"
        >{{ a.name }}</span>
        <span v-if="store.activeNotes.length === 0" class="active-empty">--</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.visualizer {
  height: 100%;
  display: flex;
  flex-direction: column;
  background: rgba(15, 23, 42, 0.8);
  border-left: 1px solid rgba(99, 102, 241, 0.3);
  padding: 16px;
  box-shadow: inset 0 0 20px rgba(99, 102, 241, 0.05);
}

.viz-header {
  margin-bottom: 12px;
}

.viz-title {
  margin: 0 0 8px 0;
  font-size: 16px;
  font-weight: 600;
  color: #E2E8F0;
  text-align: center;
  letter-spacing: 1px;
}

.viz-legend {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  font-size: 11px;
  color: #94A3B8;
}

.legend-dot {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  display: inline-block;
}

.legend-dot.low {
  background: #4F46E5;
  box-shadow: 0 0 6px rgba(79, 70, 229, 0.6);
}

.legend-dot.high {
  background: #7C3AED;
  box-shadow: 0 0 6px rgba(124, 58, 237, 0.6);
}

.viz-canvas-wrap {
  flex: 1;
  position: relative;
  border-radius: 8px;
  background: rgba(2, 6, 23, 0.7);
  border: 1px solid rgba(99, 102, 241, 0.2);
  overflow: hidden;
}

.viz-canvas {
  width: 100%;
  height: 100%;
  display: block;
}

.viz-empty {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  pointer-events: none;
}

.empty-hint {
  font-size: 12px;
  color: rgba(148, 163, 184, 0.5);
}

.active-notes {
  margin-top: 12px;
  padding: 10px;
  border-radius: 6px;
  background: rgba(30, 41, 59, 0.6);
  border: 1px solid rgba(99, 102, 241, 0.15);
}

.active-label {
  font-size: 11px;
  color: #94A3B8;
  margin-bottom: 6px;
}

.active-list {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  min-height: 22px;
  align-items: center;
}

.active-badge {
  font-size: 10px;
  font-weight: 600;
  color: #fff;
  padding: 3px 7px;
  border-radius: 10px;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.4);
  box-shadow: 0 0 6px rgba(0, 0, 0, 0.2);
  animation: badgeIn 0.2s ease;
}

.active-empty {
  font-size: 11px;
  color: rgba(148, 163, 184, 0.4);
}

@keyframes badgeIn {
  from { transform: scale(0.6); opacity: 0; }
  to { transform: scale(1); opacity: 1; }
}
</style>

// cp1_6.22_auto18/src/Visualizer.tsx
import { useEffect, useRef } from 'react'
import type { AudioEngine } from './AudioEngine'

export type VisualizerType = 'bars' | 'particles' | 'waveform'

interface Particle {
  angle: number
  radius: number
  speed: number
  size: number
  alpha: number
  hue: number
}

interface VisualizerProps {
  audioEngine: AudioEngine | null
  effectType: VisualizerType
  gains: { low: number; mid: number; high: number }
}

export default function Visualizer({ audioEngine, effectType, gains }: VisualizerProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const rafRef = useRef<number>(0)
  const particlesRef = useRef<Particle[]>([])
  const hueRef = useRef<number>(0)
  const typeRef = useRef<VisualizerType>(effectType)

  useEffect(() => {
    typeRef.current = effectType
  }, [effectType])

  useEffect(() => {
    const canvas = canvasRef.current
    if (!canvas) return
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    const resize = () => {
      const dpr = window.devicePixelRatio || 1
      const rect = canvas.getBoundingClientRect()
      canvas.width = Math.floor(rect.width * dpr)
      canvas.height = Math.floor(rect.height * dpr)
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0)
    }

    resize()
    window.addEventListener('resize', resize)

    const initParticles = (count: number) => {
      const arr: Particle[] = []
      for (let i = 0; i < count; i++) {
        arr.push({
          angle: (i / count) * Math.PI * 2,
          radius: 0,
          speed: 0.002 + Math.random() * 0.004,
          size: 3,
          alpha: 0.3,
          hue: (i / count) * 360,
        })
      }
      particlesRef.current = arr
    }

    if (particlesRef.current.length === 0) {
      initParticles(128)
    }

    const drawBars = (freq: Uint8Array) => {
      const w = canvas.clientWidth
      const h = canvas.clientHeight
      const barCount = 64
      const gap = 2
      const availableW = w - (barCount + 1) * gap
      const barW = Math.max(2, availableW / barCount)
      const totalStep = barW + gap
      const startX = (w - totalStep * barCount + gap) / 2
      const baseY = h - 40
      const maxBarH = h - 100

      for (let i = 0; i < barCount; i++) {
        const idx = Math.floor((i / barCount) * (freq.length * 0.7))
        const val = freq[idx] || 0
        const barH = (val / 255) * maxBarH
        const x = startX + i * totalStep
        const y = baseY - barH

        const ratio = barH / maxBarH
        const r = Math.floor(40 + ratio * 215)
        const g = Math.floor(120 - ratio * 80)
        const b = Math.floor(255 - ratio * 200)

        ctx.fillStyle = `rgb(${r},${g},${b})`
        ctx.shadowColor = `rgba(${r},${g},${b},0.6)`
        ctx.shadowBlur = 8
        ctx.fillRect(x, y, barW, barH)
      }
      ctx.shadowBlur = 0
    }

    const drawParticles = (freq: Uint8Array) => {
      const w = canvas.clientWidth
      const h = canvas.clientHeight
      const cx = w / 2
      const cy = h / 2
      const maxRadius = Math.min(w, h) * 0.45

      hueRef.current = (hueRef.current + 0.5) % 360

      const particles = particlesRef.current
      const binCount = Math.min(freq.length, particles.length)

      ctx.globalCompositeOperation = 'lighter'

      for (let i = 0; i < particles.length; i++) {
        const p = particles[i]
        const freqIdx = Math.floor((i / particles.length) * binCount)
        const energy = (freq[freqIdx] || 0) / 255

        p.radius = 50 + energy * maxRadius
        p.size = 3 + energy * 5
        p.alpha = 0.3 + energy * 0.7
        p.angle += p.speed + energy * 0.02

        const x = cx + Math.cos(p.angle) * p.radius
        const y = cy + Math.sin(p.angle) * p.radius
        const hue = (hueRef.current + p.hue) % 360

        ctx.beginPath()
        ctx.fillStyle = `hsla(${hue},80%,60%,${p.alpha})`
        ctx.shadowColor = `hsla(${hue},80%,60%,${p.alpha})`
        ctx.shadowBlur = 15
        ctx.arc(x, y, p.size, 0, Math.PI * 2)
        ctx.fill()
      }

      ctx.globalCompositeOperation = 'source-over'
      ctx.shadowBlur = 0
    }

    const drawWaveform = (time: Uint8Array) => {
      const w = canvas.clientWidth
      const h = canvas.clientHeight
      const midY = h / 2
      const amp = (h / 2) * 0.75

      ctx.lineWidth = 3
      ctx.strokeStyle = 'rgba(255,255,255,0.8)'
      ctx.shadowColor = 'rgba(59,130,246,0.5)'
      ctx.shadowBlur = 10
      ctx.beginPath()

      for (let i = 0; i < time.length; i++) {
        const x = (i / (time.length - 1)) * w
        const v = (time[i] - 128) / 128
        const y = midY + v * amp
        if (i === 0) {
          ctx.moveTo(x, y)
        } else {
          ctx.lineTo(x, y)
        }
      }
      ctx.stroke()

      ctx.lineWidth = 3
      ctx.strokeStyle = 'rgba(100,180,255,0.2)'
      ctx.shadowBlur = 0
      ctx.beginPath()
      for (let i = 0; i < time.length; i++) {
        const x = (i / (time.length - 1)) * w
        const v = (time[i] - 128) / 128
        const y = midY - v * amp
        if (i === 0) {
          ctx.moveTo(x, y)
        } else {
          ctx.lineTo(x, y)
        }
      }
      ctx.stroke()
    }

    const drawIdle = () => {
      const w = canvas.clientWidth
      const h = canvas.clientHeight
      ctx.save()
      ctx.fillStyle = 'rgba(255,255,255,0.4)'
      ctx.font = '20px -apple-system, "PingFang SC", sans-serif'
      ctx.textAlign = 'center'
      ctx.textBaseline = 'middle'
      ctx.fillText('点击右侧"上传音频"按钮开始体验', w / 2, h / 2)
      ctx.restore()
    }

    const render = () => {
      const w = canvas.clientWidth
      const h = canvas.clientHeight
      ctx.clearRect(0, 0, w, h)

      const freq = audioEngine ? audioEngine.getFrequencyData() : new Uint8Array(0)
      const time = audioEngine ? audioEngine.getTimeDomainData() : new Uint8Array(0)
      const hasAudio = freq.length > 0 && freq.some(v => v > 0)

      if (typeRef.current === 'bars') {
        drawBars(freq)
      } else if (typeRef.current === 'particles') {
        drawParticles(freq)
      } else if (typeRef.current === 'waveform') {
        drawWaveform(time)
      }

      if (!hasAudio && !audioEngine) {
        drawIdle()
      }

      rafRef.current = requestAnimationFrame(render)
    }

    rafRef.current = requestAnimationFrame(render)

    return () => {
      cancelAnimationFrame(rafRef.current)
      window.removeEventListener('resize', resize)
    }
  }, [audioEngine, gains])

  const containerStyle: React.CSSProperties = {
    position: 'relative',
    width: '70%',
    minHeight: 600,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    boxSizing: 'border-box',
  }

  const canvasWrapperStyle: React.CSSProperties = {
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: 600,
    borderRadius: 16,
    overflow: 'hidden',
    boxShadow: '0 0 60px rgba(59,130,246,0.15), inset 0 0 40px rgba(59,130,246,0.08)',
    border: '1px solid rgba(59,130,246,0.25)',
    background: 'rgba(10,10,26,0.6)',
  }

  const cornerStyle: React.CSSProperties = {
    position: 'absolute',
    width: 30,
    height: 30,
    borderColor: 'rgba(59,130,246,0.7)',
    borderStyle: 'solid',
    pointerEvents: 'none',
  }

  return (
    <div style={containerStyle}>
      <div style={canvasWrapperStyle}>
        <div style={{ ...cornerStyle, top: 6, left: 6, borderWidth: '2px 0 0 2px', borderTopLeftRadius: 10 }} />
        <div style={{ ...cornerStyle, top: 6, right: 6, borderWidth: '2px 2px 0 0', borderTopRightRadius: 10 }} />
        <div style={{ ...cornerStyle, bottom: 6, left: 6, borderWidth: '0 0 2px 2px', borderBottomLeftRadius: 10 }} />
        <div style={{ ...cornerStyle, bottom: 6, right: 6, borderWidth: '0 2px 2px 0', borderBottomRightRadius: 10 }} />
        <canvas
          ref={canvasRef}
          style={{
            display: 'block',
            width: '100%',
            height: '100%',
            minHeight: 600,
          }}
        />
      </div>
    </div>
  )
}
