// cp2_6.20_auto36/src/components/Timeline.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { useMusicStore, getNoteColor, getNoteHeight } from '@/stores/musicStore'
import { initAudioContext, playNote } from '@/utils/audioEngine'

const store = useMusicStore()
const timelineRef = ref<HTMLDivElement | null>(null)
const playBtnRef = ref<HTMLButtonElement | null>(null)
const playBtnAnimating = ref(false)
const dragOverBeat = ref<number | null>(null)
let rafId: number | null = null

const totalWidth = computed(() => store.totalBeats * store.beatWidth)
const playheadX = computed(() => store.currentBeatFloat * store.beatWidth)

function beatLoop() {
  store.updatePlayback(performance.now())
  rafId = requestAnimationFrame(beatLoop)
}

watch(() => store.isPlaying, (playing) => {
  if (playing && rafId === null) {
    rafId = requestAnimationFrame(beatLoop)
  } else if (!playing && rafId !== null) {
    cancelAnimationFrame(rafId)
    rafId = null
  }
})

function handlePlayToggle() {
  initAudioContext()
  playBtnAnimating.value = true
  if (!store.isPlaying) {
    const beatNotes = store.placedNotes.filter(p => p.beat === store.currentBeat)
    for (const pn of beatNotes) {
      playNote(pn.id, pn.note.frequency, 300)
    }
  }
  store.togglePlay()
  setTimeout(() => {
    playBtnAnimating.value = false
  }, 300)
}

function handleReset() {
  store.resetPlayback()
}

function handleTempoInput(e: Event) {
  const value = parseFloat((e.target as HTMLInputElement).value)
  store.setTempo(value)
}

function handleDragOver(e: DragEvent) {
  e.preventDefault()
  if (!timelineRef.value) return
  const rect = timelineRef.value.getBoundingClientRect()
  const scrollLeft = timelineRef.value.scrollLeft
  const x = (e.clientX - rect.left) + scrollLeft
  const beat = Math.floor(x / store.beatWidth)
  if (beat >= 0 && beat < store.totalBeats) {
    dragOverBeat.value = beat
    if (e.dataTransfer) e.dataTransfer.dropEffect = 'copy'
  }
}

function handleDragLeave() {
  dragOverBeat.value = null
}

function handleDrop(e: DragEvent) {
  e.preventDefault()
  initAudioContext()
  const noteId = e.dataTransfer?.getData('noteId')
  const placedId = e.dataTransfer?.getData('placedNoteId')
  if (!timelineRef.value) {
    dragOverBeat.value = null
    return
  }
  const rect = timelineRef.value.getBoundingClientRect()
  const scrollLeft = timelineRef.value.scrollLeft
  const x = (e.clientX - rect.left) + scrollLeft
  const beat = Math.floor(x / store.beatWidth)
  dragOverBeat.value = null
  if (beat < 0 || beat >= store.totalBeats) return

  if (noteId) {
    const note = store.notes.find(n => n.id === noteId)
    if (note) {
      store.addNoteToTimeline(noteId, beat)
      playNote(`drop-${noteId}`, note.frequency, 200)
    }
  } else if (placedId) {
    const pn = store.placedNotes.find(p => p.id === placedId)
    if (pn) {
      store.removeNoteById(placedId)
      store.addNoteToTimeline(pn.noteId, beat)
      playNote(`move-${placedId}`, pn.note.frequency, 200)
    }
  }
}

function handleNoteDragStart(e: DragEvent, placedId: string, noteId: string) {
  if (e.dataTransfer) {
    e.dataTransfer.setData('placedNoteId', placedId)
    e.dataTransfer.setData('noteId', noteId)
    e.dataTransfer.effectAllowed = 'move'
  }
}

function handleNoteClick(placedId: string, e: MouseEvent) {
  e.stopPropagation()
  store.selectNote(store.selectedNoteId === placedId ? null : placedId)
}

function handleTimelineClick() {
  store.selectNote(null)
}

function handleKeydown(e: KeyboardEvent) {
  if (e.key === 'Delete' || e.key === 'Backspace') {
    if (store.selectedNoteId) {
      store.removeSelectedNote()
    }
  }
}

onMounted(() => {
  window.addEventListener('keydown', handleKeydown)
  nextTick(() => {
    if (timelineRef.value) {
      timelineRef.value.scrollLeft = 0
    }
  })
})

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeydown)
  if (rafId) cancelAnimationFrame(rafId)
})
</script>

<template>
  <div class="timeline-wrapper" @click="handleTimelineClick">
    <div class="timeline-header">
      <h3 class="timeline-title">时间轴</h3>
      <div class="beat-info">
        拍子: {{ Math.floor(store.currentBeat) + 1 }} / {{ store.totalBeats }}
      </div>
    </div>

    <div
      ref="timelineRef"
      class="timeline-scroll"
      @dragover="handleDragOver"
      @dragleave="handleDragLeave"
      @drop="handleDrop"
    >
      <div class="timeline-inner" :style="{ width: totalWidth + 'px' }">
        <div class="beat-ruler">
          <div
            v-for="b in store.totalBeats"
            :key="b"
            class="beat-mark"
            :class="{ 'beat-major': (b - 1) % 4 === 0, 'beat-hover': dragOverBeat === b - 1 }"
            :style="{ left: (b - 1) * store.beatWidth + 'px' }"
          >
            <span v-if="(b - 1) % 4 === 0" class="beat-num">{{ b }}</span>
          </div>
        </div>

        <div class="timeline-track">
          <div
            v-for="pn in store.placedNotes"
            :key="pn.id"
            class="placed-note"
            :class="{ selected: store.selectedNoteId === pn.id, resetting: store.isResetting }"
            draggable="true"
            :style="{
              left: pn.beat * store.beatWidth + ((store.beatWidth - 30) / 2) + 'px',
              bottom: '8px',
              height: getNoteHeight(pn.note.index) + 'px',
              background: `linear-gradient(180deg, ${getNoteColor(pn.note.index)} 0%, ${getNoteColor(pn.note.index)}cc 100%)`
            }"
            @click="(e) => handleNoteClick(pn.id, e)"
            @dragstart="(e) => handleNoteDragStart(e, pn.id, pn.noteId)"
          >
            <span class="placed-note-label">{{ pn.note.name }}</span>
          </div>

          <div
            class="playhead"
            :style="{
              transform: `translateX(${playheadX}px)`,
              opacity: store.isResetting ? 0 : 1
            }"
          ></div>
        </div>
      </div>
    </div>

    <div class="controls">
      <button
        ref="playBtnRef"
        class="control-btn play-btn"
        :class="{ playing: store.isPlaying, animating: playBtnAnimating }"
        @click="handlePlayToggle"
      >
        <svg v-if="!store.isPlaying" class="icon" viewBox="0 0 24 24" fill="currentColor">
          <polygon points="6,4 20,12 6,20" />
        </svg>
        <svg v-else class="icon" viewBox="0 0 24 24" fill="currentColor">
          <rect x="6" y="4" width="4" height="16" />
          <rect x="14" y="4" width="4" height="16" />
        </svg>
      </button>

      <button class="control-btn reset-btn" @click="handleReset">
        <svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M3 12a9 9 0 1 0 3-6.7L3 8" />
          <polyline points="3 3 3 8 8 8" />
        </svg>
      </button>

      <div class="tempo-control">
        <span class="tempo-label">速度</span>
        <div class="slider-wrap">
          <input
            type="range"
            min="0.5"
            max="2.0"
            step="0.1"
            :value="store.tempo"
            class="tempo-slider"
            @input="handleTempoInput"
          />
          <span class="tempo-value" :style="{ left: ((store.tempo - 0.5) / 1.5) * 100 + '%' }">
            {{ store.tempo.toFixed(1) }}x
          </span>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.timeline-wrapper {
  height: 100%;
  display: flex;
  flex-direction: column;
  background: rgba(15, 23, 42, 0.95);
}

.timeline-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 20px;
  border-bottom: 1px solid rgba(99, 102, 241, 0.2);
}

.timeline-title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: #E2E8F0;
  letter-spacing: 1px;
}

.beat-info {
  font-size: 13px;
  color: #94A3B8;
  font-variant-numeric: tabular-nums;
}

.timeline-scroll {
  flex: 1;
  overflow-x: auto;
  overflow-y: hidden;
  position: relative;
  padding: 10px 0;
  scroll-behavior: smooth;
}

.timeline-scroll::-webkit-scrollbar {
  height: 6px;
}

.timeline-scroll::-webkit-scrollbar-track {
  background: rgba(30, 41, 59, 0.6);
  border-radius: 3px;
}

.timeline-scroll::-webkit-scrollbar-thumb {
  background: linear-gradient(90deg, #4F46E5, #6366F1);
  border-radius: 3px;
}

.timeline-scroll::-webkit-scrollbar-thumb:hover {
  background: linear-gradient(90deg, #6366F1, #7C3AED);
}

.timeline-inner {
  position: relative;
  height: 100%;
  min-width: 100%;
}

.beat-ruler {
  position: relative;
  height: 24px;
  border-bottom: 1px solid rgba(99, 102, 241, 0.15);
  margin: 0 10px;
}

.beat-mark {
  position: absolute;
  width: 40px;
  height: 100%;
  display: flex;
  align-items: flex-start;
  justify-content: flex-start;
  padding-left: 2px;
  transition: background 0.15s;
}

.beat-mark::before {
  content: '';
  position: absolute;
  left: 0;
  bottom: 0;
  width: 1px;
  height: 8px;
  background: rgba(99, 102, 241, 0.3);
}

.beat-mark.beat-major::before {
  height: 14px;
  background: rgba(99, 102, 241, 0.6);
}

.beat-mark.beat-hover {
  background: rgba(245, 158, 11, 0.15);
  border-radius: 4px 4px 0 0;
}

.beat-mark.beat-hover::before {
  background: #F59E0B;
  height: 16px;
}

.beat-num {
  font-size: 10px;
  color: #64748B;
  font-weight: 500;
}

.timeline-track {
  position: relative;
  height: calc(100% - 40px);
  margin: 8px 10px 0;
  background:
    repeating-linear-gradient(
      90deg,
      transparent 0px,
      transparent 39px,
      rgba(99, 102, 241, 0.05) 39px,
      rgba(99, 102, 241, 0.05) 40px
    );
  border-radius: 4px;
  overflow: hidden;
}

.placed-note {
  position: absolute;
  width: 30px;
  border-radius: 5px;
  border: 1px solid rgba(99, 102, 241, 0.35);
  cursor: grab;
  transition: box-shadow 0.2s, opacity 0.25s, transform 0.2s;
  display: flex;
  align-items: flex-start;
  justify-content: center;
  padding-top: 4px;
  user-select: none;
}

.placed-note:hover {
  transform: translateY(-2px);
}

.placed-note:active {
  cursor: grabbing;
}

.placed-note.selected {
  box-shadow: 0 0 5px #F59E0B, 0 0 12px rgba(245, 158, 11, 0.5);
  border-color: #F59E0B;
}

.placed-note.resetting {
  animation: noteReset 0.5s ease;
}

@keyframes noteReset {
  0% { opacity: 1; }
  50% { opacity: 0; }
  100% { opacity: 1; }
}

.placed-note-label {
  font-size: 9px;
  font-weight: 600;
  color: #fff;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
}

.playhead {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 2px;
  background: linear-gradient(180deg, #EF4444, #DC2626);
  box-shadow: 0 0 8px rgba(239, 68, 68, 0.7);
  transition: transform 0.08s linear, opacity 0.25s;
  pointer-events: none;
  z-index: 5;
}

.playhead::before {
  content: '';
  position: absolute;
  top: -6px;
  left: -5px;
  width: 12px;
  height: 12px;
  background: #EF4444;
  transform: rotate(45deg);
  box-shadow: 0 0 8px rgba(239, 68, 68, 0.8);
}

.controls {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 14px 20px;
  border-top: 1px solid rgba(99, 102, 241, 0.2);
  background: rgba(15, 23, 42, 0.9);
}

.control-btn {
  width: 44px;
  height: 44px;
  border-radius: 50%;
  border: 1px solid rgba(99, 102, 241, 0.35);
  background: rgba(30, 41, 59, 0.8);
  color: #E2E8F0;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 0 8px rgba(99, 102, 241, 0.2);
  transition: background 0.3s ease, color 0.3s ease, box-shadow 0.3s ease;
}

.play-btn.animating {
  animation: spinAndColor 0.3s ease;
}

.play-btn.playing {
  background: linear-gradient(135deg, #4F46E5, #7C3AED);
  color: #fff;
  box-shadow: 0 0 14px rgba(124, 58, 237, 0.5);
}

@keyframes spinAndColor {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

.control-btn:hover {
  box-shadow: 0 0 14px rgba(99, 102, 241, 0.5);
}

.control-btn:active {
  transform: scale(0.92);
}

.icon {
  width: 20px;
  height: 20px;
}

.tempo-control {
  flex: 1;
  display: flex;
  align-items: center;
  gap: 12px;
  max-width: 360px;
}

.tempo-label {
  font-size: 13px;
  color: #94A3B8;
  min-width: 32px;
}

.slider-wrap {
  flex: 1;
  position: relative;
  padding-top: 4px;
}

.tempo-slider {
  width: 100%;
  height: 4px;
  border-radius: 2px;
  background: rgba(30, 41, 59, 0.9);
  outline: none;
  -webkit-appearance: none;
  appearance: none;
  cursor: pointer;
}

.tempo-slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: linear-gradient(135deg, #4F46E5, #7C3AED);
  cursor: pointer;
  box-shadow: 0 0 8px rgba(99, 102, 241, 0.6);
  transition: transform 0.15s;
}

.tempo-slider::-webkit-slider-thumb:hover {
  transform: scale(1.2);
}

.tempo-slider::-moz-range-thumb {
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background: linear-gradient(135deg, #4F46E5, #7C3AED);
  cursor: pointer;
  border: none;
  box-shadow: 0 0 8px rgba(99, 102, 241, 0.6);
}

.tempo-value {
  position: absolute;
  top: -18px;
  transform: translateX(-50%);
  font-size: 11px;
  font-weight: 600;
  color: #F59E0B;
  background: rgba(30, 41, 59, 0.95);
  padding: 2px 6px;
  border-radius: 4px;
  border: 1px solid rgba(245, 158, 11, 0.4);
  white-space: nowrap;
  font-variant-numeric: tabular-nums;
  pointer-events: none;
  transition: left 0.05s;
}
</style>

// cp1_duo_6.22_auto23/src/ui/Timeline.tsx
import React, { useRef, useState, useCallback, useEffect } from 'react';
import { Subtitle, TIMELINE_MAX_DURATION, SUBTITLE_COLORS } from '../types';

type DragType = 'move' | 'left' | 'right' | null;

interface TimelineProps {
  subtitles: Subtitle[];
  onSubtitleUpdate: (id: string, updates: Partial<Subtitle>) => void;
  selectedSubtitleId: string | null;
  onSelectSubtitle: (id: string | null) => void;
}

export const Timeline: React.FC<TimelineProps> = ({
  subtitles,
  onSubtitleUpdate,
  selectedSubtitleId,
  onSelectSubtitle,
}) => {
  const timelineRef = useRef<HTMLDivElement>(null);
  const [timelineWidth, setTimelineWidth] = useState(0);
  const [dragging, setDragging] = useState<{
    id: string;
    type: DragType;
    startX: number;
    startStartTime: number;
    startDuration: number;
  } | null>(null);

  const ROW_HEIGHT = 40;
  const TICK_HEIGHT = 24;
  const PADDING_LEFT = 60;

  useEffect(() => {
    const updateWidth = () => {
      if (timelineRef.current) {
        setTimelineWidth(timelineRef.current.clientWidth - PADDING_LEFT);
      }
    };
    updateWidth();
    window.addEventListener('resize', updateWidth);
    return () => window.removeEventListener('resize', updateWidth);
  }, []);

  const getBarColor = (index: number): string => {
    return SUBTITLE_COLORS[index % SUBTITLE_COLORS.length];
  };

  const timeToPixel = (time: number): number => {
    return (time / TIMELINE_MAX_DURATION) * timelineWidth;
  };

  const pixelToTime = (pixel: number): number => {
    const ratio = pixel / timelineWidth;
    return Math.max(0, Math.min(TIMELINE_MAX_DURATION, ratio * TIMELINE_MAX_DURATION));
  };

  const handleMouseDown = useCallback((
    e: React.MouseEvent,
    subtitle: Subtitle,
    type: DragType
  ) => {
    e.preventDefault();
    e.stopPropagation();
    onSelectSubtitle(subtitle.id);
    setDragging({
      id: subtitle.id,
      type,
      startX: e.clientX,
      startStartTime: subtitle.startTime,
      startDuration: subtitle.duration,
    });
  }, [onSelectSubtitle]);

  useEffect(() => {
    if (!dragging) return;

    const handleMouseMove = (e: MouseEvent) => {
      if (!timelineRef.current) return;
      const rect = timelineRef.current.getBoundingClientRect();
      const relX = e.clientX - rect.left - PADDING_LEFT;
      const deltaTime = pixelToTime(relX) - pixelToTime(dragging.startX - rect.left - PADDING_LEFT);

      const subtitle = subtitles.find(s => s.id === dragging.id);
      if (!subtitle) return;

      if (dragging.type === 'move') {
        let newStartTime = Math.max(0, Math.min(
          TIMELINE_MAX_DURATION - subtitle.duration,
          dragging.startStartTime + deltaTime
        ));
        newStartTime = Math.round(newStartTime * 10) / 10;
        onSubtitleUpdate(dragging.id, { startTime: newStartTime });
      } else if (dragging.type === 'left') {
        const timeDelta = Math.max(0.1, dragging.startDuration - deltaTime);
        const newDuration = Math.round(timeDelta * 10) / 10;
        const maxDuration = TIMELINE_MAX_DURATION - dragging.startStartTime;
        const finalDuration = Math.min(newDuration, maxDuration);
        if (finalDuration >= 0.1) {
          const newStartTime = Math.max(0, Math.min(
            TIMELINE_MAX_DURATION - 0.1,
            dragging.startStartTime + (dragging.startDuration - finalDuration)
          ));
          const roundedStartTime = Math.round(newStartTime * 10) / 10;
          onSubtitleUpdate(dragging.id, {
            startTime: roundedStartTime,
            duration: finalDuration,
          });
        }
      } else if (dragging.type === 'right') {
        const newDuration = Math.max(0.1, dragging.startDuration + deltaTime);
        const maxDuration = TIMELINE_MAX_DURATION - subtitle.startTime;
        const finalDuration = Math.min(newDuration, maxDuration);
        const rounded = Math.round(finalDuration * 10) / 10;
        if (rounded >= 0.1) {
          onSubtitleUpdate(dragging.id, { duration: rounded });
        }
      }
    };

    const handleMouseUp = () => {
      setDragging(null);
    };

    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);

    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [dragging, subtitles, onSubtitleUpdate]);

  const handleTimelineClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget || (e.target as HTMLElement).classList.contains('timeline-content')) {
      onSelectSubtitle(null);
    }
  };

  const ticks = [];
  for (let i = 0; i <= TIMELINE_MAX_DURATION; i += 5) {
    ticks.push(i);
  }

  const minorTicks = [];
  for (let i = 0; i <= TIMELINE_MAX_DURATION; i++) {
    minorTicks.push(i);
  }

  return (
    <div className="timeline-wrapper" onClick={handleTimelineClick}>
      <style>{`
        .timeline-wrapper {
          background: rgba(0, 0, 0, 0.2);
          border-radius: 8px;
          padding: 12px;
          margin-bottom: 16px;
          user-select: none;
        }

        .timeline-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 8px;
        }

        .timeline-title {
          font-size: 13px;
          font-weight: 600;
          color: var(--text-primary);
          display: flex;
          align-items: center;
          gap: 6px;
        }

        .timeline-hint {
          font-size: 11px;
          color: var(--text-secondary);
        }

        .timeline {
          position: relative;
          overflow-x: auto;
        }

        .timeline-content {
          position: relative;
          padding-left: ${PADDING_LEFT}px;
          padding-top: ${TICK_HEIGHT}px;
        }

        .timeline-ticks {
          position: absolute;
          top: 0;
          left: ${PADDING_LEFT}px;
          right: 0;
          height: ${TICK_HEIGHT}px;
          border-bottom: 1px solid var(--border-color);
        }

        .timeline-tick {
          position: absolute;
          top: 0;
          font-size: 10px;
          color: var(--text-secondary);
          transform: translateX(-50%);
          display: flex;
          flex-direction: column;
          align-items: center;
        }

        .timeline-tick::before {
          content: '';
          display: block;
          width: 1px;
          height: 8px;
          background: var(--border-color);
          margin-bottom: 2px;
        }

        .timeline-tick.minor::before {
          height: 4px;
          opacity: 0.5;
        }

        .timeline-row-labels {
          position: absolute;
          left: 0;
          top: ${TICK_HEIGHT}px;
          width: ${PADDING_LEFT - 8}px;
        }

        .timeline-row-label {
          height: ${ROW_HEIGHT}px;
          display: flex;
          align-items: center;
          justify-content: flex-end;
          padding-right: 8px;
          font-size: 11px;
          color: var(--text-secondary);
          font-weight: 500;
        }

        .timeline-rows {
          position: relative;
        }

        .timeline-row {
          position: relative;
          height: ${ROW_HEIGHT}px;
          border-bottom: 1px solid rgba(255, 255, 255, 0.05);
        }

        .timeline-row-grid {
          position: absolute;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background-image: repeating-linear-gradient(
            to right,
            transparent,
            transparent calc(100% / ${TIMELINE_MAX_DURATION / 5} - 1px),
            rgba(255, 255, 255, 0.05) calc(100% / ${TIMELINE_MAX_DURATION / 5} - 1px),
            rgba(255, 255, 255, 0.05) calc(100% / ${TIMELINE_MAX_DURATION / 5})
          );
        }

        .subtitle-bar {
          position: absolute;
          top: 6px;
          height: ${ROW_HEIGHT - 12}px;
          border-radius: 6px;
          cursor: grab;
          display: flex;
          align-items: center;
          padding: 0 10px;
          font-size: 12px;
          color: white;
          font-weight: 500;
          overflow: hidden;
          white-space: nowrap;
          text-overflow: ellipsis;
          transition: box-shadow 0.2s ease, transform 0.1s ease;
          box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
        }

        .subtitle-bar:hover {
          box-shadow: 0 4px 16px rgba(0, 0, 0, 0.5);
          z-index: 10;
        }

        .subtitle-bar.selected {
          outline: 2px solid #ffffff;
          outline-offset: 1px;
          z-index: 20;
        }

        .subtitle-bar:active {
          cursor: grabbing;
        }

        .subtitle-bar-text {
          flex: 1;
          overflow: hidden;
          text-overflow: ellipsis;
          pointer-events: none;
          text-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);
        }

        .subtitle-bar-resize {
          position: absolute;
          top: 0;
          bottom: 0;
          width: 8px;
          cursor: ew-resize;
          display: flex;
          align-items: center;
          justify-content: center;
          opacity: 0;
          transition: opacity 0.2s ease;
        }

        .subtitle-bar:hover .subtitle-bar-resize {
          opacity: 1;
        }

        .subtitle-bar-resize.left {
          left: 0;
          border-top-left-radius: 6px;
          border-bottom-left-radius: 6px;
        }

        .subtitle-bar-resize.right {
          right: 0;
          border-top-right-radius: 6px;
          border-bottom-right-radius: 6px;
        }

        .subtitle-bar-resize-handle {
          width: 3px;
          height: 16px;
          background: rgba(255, 255, 255, 0.7);
          border-radius: 2px;
        }

        .timeline-empty {
          text-align: center;
          padding: 24px 12px;
          color: var(--text-secondary);
          font-size: 12px;
          font-style: italic;
        }
      `}</style>

      <div className="timeline-header">
        <span className="timeline-title">
          <span>⏱</span>
          时间轴编排
        </span>
        <span className="timeline-hint">拖拽条块调整时间，拖拽边缘调整时长</span>
      </div>

      {subtitles.length === 0 ? (
        <div className="timeline-empty">暂无字幕，请先添加字幕</div>
      ) : (
        <div className="timeline" ref={timelineRef}>
          <div className="timeline-content">
            <div className="timeline-ticks">
              {ticks.map((tick) => (
                <div
                  key={tick}
                  className="timeline-tick"
                  style={{ left: `${timeToPixel(tick)}px` }}
                >
                  {tick}s
                </div>
              ))}
              {minorTicks.filter(t => t % 5 !== 0).map((tick) => (
                <div
                  key={`minor-${tick}`}
                  className="timeline-tick minor"
                  style={{ left: `${timeToPixel(tick)}px` }}
                />
              ))}
            </div>

            <div className="timeline-row-labels">
              {subtitles.map((_, index) => (
                <div key={index} className="timeline-row-label">
                  第{index + 1}条
                </div>
              ))}
            </div>

            <div className="timeline-rows">
              {subtitles.map((subtitle, index) => {
                const left = timeToPixel(subtitle.startTime);
                const width = timeToPixel(subtitle.duration);
                const color = getBarColor(index);
                const isSelected = selectedSubtitleId === subtitle.id;

                return (
                  <div key={subtitle.id} className="timeline-row">
                    <div className="timeline-row-grid" />
                    <div
                      className={`subtitle-bar ${isSelected ? 'selected' : ''}`}
                      style={{
                        left: `${left}px`,
                        width: `${Math.max(width, 20)}px`,
                        top: `${index * ROW_HEIGHT + 6}px`,
                        background: `linear-gradient(135deg, ${color}, ${color}dd)`,
                      }}
                      onMouseDown={(e) => handleMouseDown(e, subtitle, 'move')}
                      onClick={(e) => {
                        e.stopPropagation();
                        onSelectSubtitle(subtitle.id);
                      }}
                    >
                      <div
                        className="subtitle-bar-resize left"
                        onMouseDown={(e) => handleMouseDown(e, subtitle, 'left')}
                      >
                        <div className="subtitle-bar-resize-handle" />
                      </div>
                      <span className="subtitle-bar-text">
                        {subtitle.text || `字幕 ${index + 1}`}
                      </span>
                      <div
                        className="subtitle-bar-resize right"
                        onMouseDown={(e) => handleMouseDown(e, subtitle, 'right')}
                      >
                        <div className="subtitle-bar-resize-handle" />
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
