// cp1_6.19_auto16/src/components/KanbanBoard.tsx
import React, { useState, useRef, useCallback } from 'react';
import { useTaskStore, Task } from '../store/taskStore';
import TimerPanel from './TimerPanel';

const statusConfig = {
  todo: {
    title: '待办',
    bgColor: '#fee2e2',
    badgeColor: '#fecaca',
    textColor: '#991b1b'
  },
  'in-progress': {
    title: '进行中',
    bgColor: '#fef3c7',
    badgeColor: '#fde68a',
    textColor: '#92400e'
  },
  done: {
    title: '已完成',
    bgColor: '#d1fae5',
    badgeColor: '#a7f3d0',
    textColor: '#065f46'
  }
};

const priorityConfig = {
  high: { label: '高', color: '#ef4444' },
  medium: { label: '中', color: '#f59e0b' },
  low: { label: '低', color: '#22c55e' }
};

function formatRelativeTime(timestamp: number): string {
  const now = Date.now();
  const diff = now - timestamp;
  const minutes = Math.floor(diff / 60000);
  const hours = Math.floor(diff / 3600000);
  const days = Math.floor(diff / 86400000);

  if (diff < 60000) return '刚刚';
  if (minutes < 60) return `${minutes}分钟前`;
  if (hours < 24) return `${hours}小时前`;
  return `${days}天前`;
}

interface TaskCardProps {
  task: Task;
  onDragStart: (e: React.DragEvent, taskId: string) => void;
  onDragEnd: () => void;
  onClick: () => void;
}

const TaskCard: React.FC<TaskCardProps> = ({ task, onDragStart, onDragEnd, onClick }) => {
  const startTimer = useTaskStore(state => state.startTimer);
  const pauseTimer = useTaskStore(state => state.pauseTimer);
  const [isDragging, setIsDragging] = useState(false);

  const handleDragStart = (e: React.DragEvent) => {
    setIsDragging(true);
    onDragStart(e, task.id);
  };

  const handleDragEnd = () => {
    setIsDragging(false);
    onDragEnd();
  };

  const handleTimerClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (task.isRunning) {
      pauseTimer(task.id);
    } else {
      startTimer(task.id);
    }
  };

  const priority = priorityConfig[task.priority];

  return (
    <div
      className={`task-card ${isDragging ? 'dragging' : ''}`}
      draggable
      onDragStart={handleDragStart}
      onDragEnd={handleDragEnd}
      onClick={onClick}
    >
      <div className="task-card-header">
        <span
          className="priority-tag"
          style={{ backgroundColor: priority.color + '20', color: priority.color }}
        >
          {priority.label}
        </span>
        <button
          className={`timer-btn ${task.isRunning ? 'running' : ''}`}
          onClick={handleTimerClick}
        >
          {task.isRunning ? (
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <rect x="6" y="4" width="4" height="16" />
              <rect x="14" y="4" width="4" height="16" />
            </svg>
          ) : (
            <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
              <polygon points="5,3 19,12 5,21" />
            </svg>
          )}
        </button>
      </div>
      <h4 className="task-title">{task.title}</h4>
      <div className="task-meta">
        <span className="task-time">{formatRelativeTime(task.createdAt)}</span>
      </div>

      <style>{`
        .task-card {
          background: white;
          border-radius: 12px;
          padding: 16px;
          margin-bottom: 12px;
          box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
          cursor: pointer;
          transition: all 0.2s ease;
        }
        .task-card:hover {
          transform: translateY(-6px);
          box-shadow: 0 8px 24px rgba(0, 0, 0, 0.2);
        }
        .task-card.dragging {
          opacity: 0.7;
          transform: rotate(3deg);
        }
        .task-card-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 10px;
        }
        .priority-tag {
          padding: 3px 8px;
          border-radius: 6px;
          font-size: 0.7rem;
          font-weight: 600;
        }
        .timer-btn {
          width: 32px;
          height: 32px;
          border-radius: 50%;
          border: none;
          background: transparent;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          color: #4f46e5;
          transition: all 0.15s ease;
        }
        .timer-btn:hover {
          background: #dbeafe;
        }
        .timer-btn:active {
          transform: scale(0.9);
        }
        .timer-btn.running {
          color: #ef4444;
          animation: pulse 2s ease-in-out infinite;
        }
        @keyframes pulse {
          0%, 100% { transform: rotate(0deg); }
          50% { transform: rotate(180deg); }
        }
        .task-title {
          margin: 0 0 8px 0;
          font-size: 0.95rem;
          font-weight: 600;
          color: #1f2937;
          line-height: 1.4;
        }
        .task-meta {
          display: flex;
          justify-content: space-between;
          align-items: center;
        }
        .task-time {
          font-size: 0.75rem;
          color: #9ca3af;
        }
      `}</style>
    </div>
  );
};

interface ColumnProps {
  status: 'todo' | 'in-progress' | 'done';
  tasks: Task[];
  onDragStart: (e: React.DragEvent, taskId: string) => void;
  onDragEnd: () => void;
  onDrop: (status: Task['status']) => void;
  onDragOver: (e: React.DragEvent) => void;
  isDragOver: boolean;
  onTaskClick: (task: Task) => void;
}

const Column: React.FC<ColumnProps> = ({
  status,
  tasks,
  onDragStart,
  onDragEnd,
  onDrop,
  onDragOver,
  isDragOver,
  onTaskClick
}) => {
  const config = statusConfig[status];

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    onDrop(status);
  };

  return (
    <div
      className={`kanban-column ${isDragOver ? 'drag-over' : ''}`}
      style={{ backgroundColor: config.bgColor }}
      onDragOver={onDragOver}
      onDrop={handleDrop}
    >
      <div className="column-header">
        <h3 className="column-title">{config.title}</h3>
        <span
          className="task-count"
          style={{ backgroundColor: config.badgeColor, color: config.textColor }}
        >
          {tasks.length}
        </span>
      </div>
      <div className="task-list">
        {tasks.map(task => (
          <TaskCard
            key={task.id}
            task={task}
            onDragStart={onDragStart}
            onDragEnd={onDragEnd}
            onClick={() => onTaskClick(task)}
          />
        ))}
      </div>

      <style>{`
        .kanban-column {
          flex: 1;
          min-width: 280px;
          border-radius: 12px;
          padding: 16px;
          transition: all 0.3s ease-out;
        }
        .kanban-column.drag-over {
          transform: scale(1.02);
          box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
        }
        .column-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 16px;
        }
        .column-title {
          margin: 0;
          font-size: 1rem;
          font-weight: 600;
          color: #1f2937;
        }
        .task-count {
          padding: 4px 10px;
          border-radius: 8px;
          font-size: 0.8rem;
          font-weight: 600;
        }
        .task-list {
          min-height: 100px;
        }
      `}</style>
    </div>
  );
};

const KanbanBoard: React.FC = () => {
  const tasks = useTaskStore(state => state.tasks);
  const selectedProjectId = useTaskStore(state => state.selectedProjectId);
  const moveTask = useTaskStore(state => state.moveTask);
  const createTask = useTaskStore(state => state.createTask);
  const setSelectedTask = useTaskStore(state => state.setSelectedTask);
  const getTasksByStatus = useTaskStore(state => state.getTasksByStatus);

  const [draggedTaskId, setDraggedTaskId] = useState<string | null>(null);
  const [dragOverStatus, setDragOverStatus] = useState<string | null>(null);
  const [showAddTask, setShowAddTask] = useState(false);
  const [newTaskTitle, setNewTaskTitle] = useState('');
  const [newTaskDesc, setNewTaskDesc] = useState('');
  const [newTaskPriority, setNewTaskPriority] = useState<Task['priority']>('medium');

  const handleDragStart = useCallback((e: React.DragEvent, taskId: string) => {
    setDraggedTaskId(taskId);
    e.dataTransfer.effectAllowed = 'move';
  }, []);

  const handleDragEnd = useCallback(() => {
    setDraggedTaskId(null);
    setDragOverStatus(null);
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'move';
  }, []);

  const handleDrop = useCallback((status: Task['status']) => {
    if (draggedTaskId) {
      moveTask(draggedTaskId, status);
    }
    setDraggedTaskId(null);
    setDragOverStatus(null);
  }, [draggedTaskId, moveTask]);

  const handleColumnDragEnter = (status: string) => {
    setDragOverStatus(status);
  };

  const handleColumnDragLeave = () => {
    setDragOverStatus(null);
  };

  const handleAddTask = () => {
    if (newTaskTitle.trim() && selectedProjectId) {
      createTask(selectedProjectId, newTaskTitle.trim(), newTaskDesc.trim(), newTaskPriority);
      setNewTaskTitle('');
      setNewTaskDesc('');
      setNewTaskPriority('medium');
      setShowAddTask(false);
    }
  };

  const handleTaskClick = (task: Task) => {
    setSelectedTask(task);
  };

  const todoTasks = getTasksByStatus('todo');
  const inProgressTasks = getTasksByStatus('in-progress');
  const doneTasks = getTasksByStatus('done');

  if (!selectedProjectId) {
    return (
      <div className="kanban-container empty">
        <div className="empty-state">
          <p>请选择一个项目或创建新项目</p>
        </div>
        <style>{`
          .kanban-container.empty {
            flex: 1;
            display: flex;
            align-items: center;
            justify-content: center;
          }
          .empty-state p {
            color: #9ca3af;
            font-size: 1.1rem;
          }
        `}</style>
      </div>
    );
  }

  return (
    <div className="kanban-container">
      <div className="kanban-header">
        <h2 className="kanban-title">任务看板</h2>
        <button className="add-task-btn" onClick={() => setShowAddTask(true)}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <line x1="12" y1="5" x2="12" y2="19" />
            <line x1="5" y1="12" x2="19" y2="12" />
          </svg>
          添加任务
        </button>
      </div>

      <div className="kanban-columns">
        <Column
          status="todo"
          tasks={todoTasks}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          isDragOver={dragOverStatus === 'todo'}
          onTaskClick={handleTaskClick}
        />
        <Column
          status="in-progress"
          tasks={inProgressTasks}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          isDragOver={dragOverStatus === 'in-progress'}
          onTaskClick={handleTaskClick}
        />
        <Column
          status="done"
          tasks={doneTasks}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          isDragOver={dragOverStatus === 'done'}
          onTaskClick={handleTaskClick}
        />
      </div>

      {showAddTask && (
        <div className="modal-overlay" onClick={() => setShowAddTask(false)}>
          <div className="modal-content" onClick={e => e.stopPropagation()}>
            <h3>新建任务</h3>
            <div className="form-group">
              <label>任务标题</label>
              <input
                type="text"
                value={newTaskTitle}
                onChange={e => setNewTaskTitle(e.target.value)}
                placeholder="输入任务标题"
                autoFocus
              />
            </div>
            <div className="form-group">
              <label>任务描述</label>
              <textarea
                value={newTaskDesc}
                onChange={e => setNewTaskDesc(e.target.value)}
                placeholder="输入任务描述"
                rows={3}
              />
            </div>
            <div className="form-group">
              <label>优先级</label>
              <div className="priority-options">
                {(['high', 'medium', 'low'] as const).map(p => (
                  <button
                    key={p}
                    className={`priority-option ${newTaskPriority === p ? 'active' : ''}`}
                    style={{
                      borderColor: priorityConfig[p].color,
                      color: newTaskPriority === p ? 'white' : priorityConfig[p].color,
                      backgroundColor: newTaskPriority === p ? priorityConfig[p].color : 'transparent'
                    }}
                    onClick={() => setNewTaskPriority(p)}
                  >
                    {priorityConfig[p].label}
                  </button>
                ))}
              </div>
            </div>
            <div className="modal-actions">
              <button className="btn btn-secondary" onClick={() => setShowAddTask(false)}>
                取消
              </button>
              <button className="btn btn-primary" onClick={handleAddTask}>
                创建
              </button>
            </div>
          </div>
        </div>
      )}

      <TimerPanel />

      <style>{`
        .kanban-container {
          flex: 1;
          display: flex;
          flex-direction: column;
          padding: 24px;
          overflow: auto;
          min-width: 900px;
        }
        .kanban-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: 24px;
        }
        .kanban-title {
          margin: 0;
          font-size: 1.5rem;
          font-weight: 700;
          color: #1f2937;
        }
        .add-task-btn {
          display: flex;
          align-items: center;
          gap: 8px;
          padding: 10px 20px;
          background: #4f46e5;
          color: white;
          border: none;
          border-radius: 8px;
          cursor: pointer;
          font-size: 0.9rem;
          font-weight: 500;
          transition: background 0.2s;
        }
        .add-task-btn:hover {
          background: #4338ca;
        }
        .kanban-columns {
          display: flex;
          gap: 20px;
          flex: 1;
        }
        .modal-overlay {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          bottom: 0;
          background: rgba(0, 0, 0, 0.4);
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 100;
          animation: fadeIn 0.2s ease;
        }
        @keyframes fadeIn {
          from { opacity: 0; }
          to { opacity: 1; }
        }
        .modal-content {
          background: white;
          border-radius: 16px;
          padding: 28px;
          width: 90%;
          max-width: 500px;
          box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
          animation: slideUp 0.3s ease-out;
        }
        @keyframes slideUp {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
        .modal-content h3 {
          margin: 0 0 20px 0;
          font-size: 1.3rem;
          font-weight: 600;
          color: #1f2937;
        }
        .form-group {
          margin-bottom: 16px;
        }
        .form-group label {
          display: block;
          margin-bottom: 8px;
          font-size: 0.85rem;
          font-weight: 500;
          color: #4b5563;
        }
        .form-group input,
        .form-group textarea {
          width: 100%;
          padding: 10px 14px;
          border: 1px solid #e5e7eb;
          border-radius: 8px;
          font-size: 0.9rem;
          font-family: inherit;
          box-sizing: border-box;
          transition: border-color 0.2s;
        }
        .form-group input:focus,
        .form-group textarea:focus {
          outline: none;
          border-color: #4f46e5;
        }
        .priority-options {
          display: flex;
          gap: 10px;
        }
        .priority-option {
          flex: 1;
          padding: 10px;
          border: 2px solid;
          border-radius: 8px;
          background: transparent;
          cursor: pointer;
          font-weight: 600;
          transition: all 0.2s;
        }
        .priority-option:hover {
          transform: translateY(-2px);
        }
        .modal-actions {
          display: flex;
          justify-content: flex-end;
          gap: 12px;
          margin-top: 24px;
        }
        .btn {
          padding: 10px 20px;
          border-radius: 8px;
          border: none;
          cursor: pointer;
          font-size: 0.9rem;
          font-weight: 500;
          transition: all 0.2s;
        }
        .btn-primary {
          background: #4f46e5;
          color: white;
        }
        .btn-primary:hover {
          background: #4338ca;
        }
        .btn-secondary {
          background: #f3f4f6;
          color: #4b5563;
        }
        .btn-secondary:hover {
          background: #e5e7eb;
        }
        @media (max-width: 768px) {
          .kanban-container {
            min-width: auto;
            padding: 16px;
          }
          .kanban-columns {
            flex-direction: column;
          }
        }
      `}</style>
    </div>
  );
};

export default KanbanBoard;

// cp1_duo_6.22_auto1/src/view/KanbanBoard.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useTaskStore, type Task, type TaskStatus, type TaskPriority } from '@/data/taskStore'

const store = useTaskStore()
const editingTaskId = ref<string | null>(null)
const dragOverColumn = ref<TaskStatus | null>(null)
const showCreateModal = ref(false)
const draggingTaskId = ref<string | null>(null)
const justPlacedTaskId = ref<string | null>(null)

const newTask = ref({
  title: '',
  description: '',
  priority: 'medium' as TaskPriority,
  estimatedHours: 4,
  assigneeId: store.members[0]?.id ?? 'm1',
})

const columns: { key: TaskStatus; label: string }[] = [
  { key: 'todo', label: '待办' },
  { key: 'in_progress', label: '进行中' },
  { key: 'done', label: '已完成' },
]

function getTasksByStatus(status: TaskStatus): Task[] {
  return store.tasks.filter(t => t.status === status)
}

function getMember(assigneeId: string) {
  return store.members.find(m => m.id === assigneeId)
}

function priorityStyle(p: TaskPriority) {
  return {
    low: { bg: 'bg-emerald-500/20', text: 'text-emerald-400', label: '低' },
    medium: { bg: 'bg-amber-500/20', text: 'text-amber-400', label: '中' },
    high: { bg: 'bg-rose-500/20', text: 'text-rose-400', label: '高' },
  }[p]
}

function onDragStart(e: DragEvent, taskId: string) {
  if (e.dataTransfer) {
    e.dataTransfer.effectAllowed = 'move'
    e.dataTransfer.setData('text/task-id', taskId)
  }
  draggingTaskId.value = taskId
}

function onDragEnd() {
  draggingTaskId.value = null
}

function onDragOver(e: DragEvent, status: TaskStatus) {
  e.preventDefault()
  if (e.dataTransfer) e.dataTransfer.dropEffect = 'move'
  dragOverColumn.value = status
}

function onDragLeave(e: DragEvent, status: TaskStatus) {
  const rect = (e.currentTarget as HTMLElement).getBoundingClientRect()
  const x = e.clientX
  const y = e.clientY
  if (x < rect.left || x > rect.right || y < rect.top || y > rect.bottom) {
    dragOverColumn.value = null
  }
}

function onDrop(e: DragEvent, status: TaskStatus) {
  e.preventDefault()
  dragOverColumn.value = null
  const taskId = e.dataTransfer?.getData('text/task-id')
  if (!taskId) return
  const success = store.moveTask(taskId, status)
  if (success) {
    justPlacedTaskId.value = taskId
    setTimeout(() => {
      justPlacedTaskId.value = null
    }, 150)
  } else {
    store.pushNotification('该成员同时进行中的任务已达上限（3个）', 'warning')
  }
  draggingTaskId.value = null
}

function saveTask(taskId: string, patch: Partial<Task>) {
  store.updateTask(taskId, patch)
  editingTaskId.value = null
}

function deleteTask(taskId: string) {
  store.removeTask(taskId)
}

function handleCreateTask() {
  if (!newTask.value.title.trim()) return
  store.addTask({
    title: newTask.value.title,
    description: newTask.value.description,
    priority: newTask.value.priority,
    estimatedHours: newTask.value.estimatedHours,
    actualHours: 0,
    assigneeId: newTask.value.assigneeId,
    status: 'todo',
  })
  newTask.value = { title: '', description: '', priority: 'medium', estimatedHours: 4, assigneeId: store.members[0]?.id ?? 'm1' }
  showCreateModal.value = false
}
</script>

<template>
  <div class="kanban-wrapper">
    <div class="kanban-header">
      <h2 class="text-xl font-bold text-white tracking-wide">任务看板</h2>
      <button
        class="px-4 py-2 rounded-lg bg-[#e94560] text-white text-sm font-medium hover:brightness-110 transition-all duration-200 shadow-lg shadow-[#e94560]/20"
        @click="showCreateModal = true"
      >
        + 新建任务
      </button>
    </div>

    <div class="kanban-columns">
      <div
        v-for="col in columns"
        :key="col.key"
        class="kanban-column"
        :class="{ 'drag-over': dragOverColumn === col.key }"
        @dragover="onDragOver($event, col.key)"
        @dragleave="onDragLeave($event, col.key)"
        @drop="onDrop($event, col.key)"
      >
        <div class="column-header">
          <span class="column-title">{{ col.label }}</span>
          <span class="column-count">{{ getTasksByStatus(col.key).length }}</span>
        </div>
        <div v-if="dragOverColumn === col.key && draggingTaskId" class="column-highlight"></div>

        <div class="column-body">
          <div
            v-for="task in getTasksByStatus(col.key)"
            :key="task.id"
            class="task-card"
            :class="{
              'is-dragging': draggingTaskId === task.id,
              'just-placed': justPlacedTaskId === task.id
            }"
            draggable="true"
            @dragstart="onDragStart($event, task.id)"
            @dragend="onDragEnd"
          >
            <template v-if="editingTaskId === task.id">
              <div class="edit-form">
                <input
                  class="edit-input"
                  :value="task.title"
                  @input="saveTask(task.id, { title: ($event.target as HTMLInputElement).value })"
                  @blur="editingTaskId = null"
                  @keyup.enter="editingTaskId = null"
                  autofocus
                />
                <textarea
                  class="edit-textarea"
                  :value="task.description"
                  @input="saveTask(task.id, { description: ($event.target as HTMLTextAreaElement).value })"
                />
                <div class="edit-row">
                  <select :value="task.priority" @change="saveTask(task.id, { priority: ($event.target as HTMLSelectElement).value as TaskPriority })">
                    <option value="low">低优先级</option>
                    <option value="medium">中优先级</option>
                    <option value="high">高优先级</option>
                  </select>
                  <input
                    type="number"
                    min="0.5"
                    step="0.5"
                    class="edit-input-small"
                    :value="task.estimatedHours"
                    @input="saveTask(task.id, { estimatedHours: Number(($event.target as HTMLInputElement).value) })"
                  />
                  <select :value="task.assigneeId" @change="saveTask(task.id, { assigneeId: ($event.target as HTMLSelectElement).value })">
                    <option v-for="m in store.members" :key="m.id" :value="m.id">{{ m.name }}</option>
                  </select>
                </div>
                <button class="delete-btn" @click="deleteTask(task.id)">删除</button>
              </div>
            </template>
            <template v-else>
              <div class="card-top" @dblclick="editingTaskId = task.id">
                <span :class="['priority-tag', priorityStyle(task.priority).bg, priorityStyle(task.priority).text]">
                  {{ priorityStyle(task.priority).label }}
                </span>
                <span class="hours-badge">{{ task.estimatedHours }}h</span>
              </div>
              <h3 class="card-title">{{ task.title }}</h3>
              <p class="card-desc">{{ task.description }}</p>
              <div class="card-footer">
                <div class="avatar" :title="getMember(task.assigneeId)?.name">
                  {{ getMember(task.assigneeId)?.avatar ?? '??' }}
                </div>
                <span class="member-name">{{ getMember(task.assigneeId)?.name }}</span>
              </div>
            </template>
          </div>
        </div>
      </div>
    </div>

    <Teleport to="body">
      <div v-if="showCreateModal" class="modal-backdrop" @click.self="showCreateModal = false">
        <div class="modal">
          <h3 class="modal-title">新建任务</h3>
          <label class="field-label">标题</label>
          <input v-model="newTask.title" class="edit-input" placeholder="任务标题" />
          <label class="field-label">描述</label>
          <textarea v-model="newTask.description" class="edit-textarea" placeholder="任务描述"></textarea>
          <div class="form-grid">
            <div>
              <label class="field-label">优先级</label>
              <select v-model="newTask.priority" class="edit-input">
                <option value="low">低</option>
                <option value="medium">中</option>
                <option value="high">高</option>
              </select>
            </div>
            <div>
              <label class="field-label">预估工时</label>
              <input v-model.number="newTask.estimatedHours" type="number" min="0.5" step="0.5" class="edit-input" />
            </div>
            <div class="col-span-2">
              <label class="field-label">负责人</label>
              <select v-model="newTask.assigneeId" class="edit-input">
                <option v-for="m in store.members" :key="m.id" :value="m.id">{{ m.name }}</option>
              </select>
            </div>
          </div>
          <div class="modal-actions">
            <button class="btn-secondary" @click="showCreateModal = false">取消</button>
            <button class="btn-primary" @click="handleCreateTask">创建</button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<style scoped>
.kanban-wrapper {
  width: 100%;
  padding: 20px;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  border-radius: 16px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.3);
}

.kanban-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.kanban-columns {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 20px;
}

@media (max-width: 1024px) {
  .kanban-columns {
    grid-template-columns: 1fr;
  }
}

.kanban-column {
  position: relative;
  background: rgba(255, 255, 255, 0.03);
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 12px;
  padding: 16px;
  min-height: 400px;
  transition: all 200ms ease;
  overflow: hidden;
}

.kanban-column.drag-over {
  background: rgba(233, 69, 96, 0.08);
  border-color: rgba(233, 69, 96, 0.4);
}

.column-highlight {
  position: absolute;
  inset: 0;
  background: rgba(99, 102, 241, 0.12);
  border: 2px dashed rgba(99, 102, 241, 0.5);
  border-radius: 12px;
  pointer-events: none;
  animation: pulse 1.5s ease-in-out infinite;
  z-index: 1;
}

@keyframes pulse {
  0%, 100% {
    opacity: 0.6;
  }
  50% {
    opacity: 1;
  }
}

.column-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  padding-bottom: 12px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
  position: relative;
  z-index: 2;
}

.column-title {
  color: #fff;
  font-weight: 600;
  font-size: 15px;
  letter-spacing: 0.5px;
}

.column-count {
  background: rgba(233, 69, 96, 0.15);
  color: #e94560;
  padding: 2px 10px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
}

.column-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
  position: relative;
  z-index: 2;
}

.task-card {
  background: linear-gradient(145deg, rgba(255, 255, 255, 0.05), rgba(255, 255, 255, 0.02));
  border: 1px solid rgba(255, 255, 255, 0.06);
  border-radius: 12px;
  padding: 14px;
  cursor: grab;
  transition: transform 200ms ease, box-shadow 200ms ease, opacity 200ms ease;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.2);
  position: relative;
  z-index: 2;
}

.task-card:hover:not(.is-dragging) {
  transform: scale(1.02);
  box-shadow: 0 8px 30px rgba(233, 69, 96, 0.15);
  border-color: rgba(233, 69, 96, 0.25);
}

.task-card:active {
  cursor: grabbing;
}

.task-card.is-dragging {
  opacity: 0.8;
  transform: scale(0.95);
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.3);
}

.task-card.just-placed {
  animation: popIn 150ms ease-out;
}

@keyframes popIn {
  0% {
    transform: scale(0.95);
  }
  100% {
    transform: scale(1);
  }
}

.card-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 10px;
}

.priority-tag {
  padding: 2px 10px;
  border-radius: 6px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.5px;
}

.hours-badge {
  background: rgba(99, 102, 241, 0.15);
  color: #a5b4fc;
  padding: 2px 8px;
  border-radius: 6px;
  font-size: 11px;
  font-weight: 600;
  font-family: 'JetBrains Mono', monospace;
}

.card-title {
  color: #fff;
  font-size: 14px;
  font-weight: 600;
  margin-bottom: 6px;
  line-height: 1.4;
}

.card-desc {
  color: rgba(255, 255, 255, 0.5);
  font-size: 12px;
  line-height: 1.5;
  margin-bottom: 12px;
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}

.card-footer {
  display: flex;
  align-items: center;
  gap: 8px;
}

.avatar {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: linear-gradient(135deg, #e94560, #8b5cf6);
  color: #fff;
  font-size: 11px;
  font-weight: 700;
  display: flex;
  align-items: center;
  justify-content: center;
}

.member-name {
  color: rgba(255, 255, 255, 0.65);
  font-size: 12px;
}

.edit-form {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.edit-input,
.edit-textarea,
.edit-form select,
.form-grid select,
.modal input,
.modal select,
.modal textarea {
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  padding: 8px 12px;
  color: #fff;
  font-size: 13px;
  outline: none;
  transition: border-color 200ms ease;
}

.edit-input:focus,
.edit-textarea:focus,
.edit-form select:focus {
  border-color: #e94560;
}

.edit-textarea {
  resize: vertical;
  min-height: 60px;
}

.edit-row {
  display: flex;
  gap: 8px;
}

.edit-row select {
  flex: 1;
}

.edit-input-small {
  width: 70px;
  background: rgba(0, 0, 0, 0.3);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  padding: 8px;
  color: #fff;
  font-size: 13px;
}

.delete-btn {
  background: rgba(239, 68, 68, 0.2);
  color: #fca5a5;
  border: none;
  padding: 6px 12px;
  border-radius: 6px;
  font-size: 12px;
  cursor: pointer;
  align-self: flex-start;
  transition: background 200ms ease;
}

.delete-btn:hover {
  background: rgba(239, 68, 68, 0.35);
}

.modal-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.6);
  backdrop-filter: blur(4px);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.modal {
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  border: 1px solid rgba(255, 255, 255, 0.08);
  border-radius: 16px;
  padding: 28px;
  width: 460px;
  max-width: 92vw;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.5);
}

.modal-title {
  color: #fff;
  font-size: 18px;
  font-weight: 700;
  margin-bottom: 20px;
}

.field-label {
  display: block;
  color: rgba(255, 255, 255, 0.6);
  font-size: 12px;
  margin-bottom: 6px;
  margin-top: 12px;
}

.form-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 12px;
}

.form-grid .col-span-2 {
  grid-column: span 2;
}

.modal-actions {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  margin-top: 24px;
}

.btn-secondary {
  background: rgba(255, 255, 255, 0.06);
  color: #fff;
  border: none;
  padding: 10px 20px;
  border-radius: 8px;
  font-size: 13px;
  cursor: pointer;
  transition: background 200ms ease;
}

.btn-secondary:hover {
  background: rgba(255, 255, 255, 0.12);
}

.btn-primary {
  background: #e94560;
  color: #fff;
  border: none;
  padding: 10px 20px;
  border-radius: 8px;
  font-size: 13px;
  font-weight: 600;
  cursor: pointer;
  transition: background 200ms ease;
}

.btn-primary:hover {
  background: #f06580;
}
</style>
